var CODE_TO_LABELS = [
    null,
    ['noSym','NONE'],
    ['accidentalNatural','medRenNatural','accidentalNaturalArabic','NATURAL'],
    ['accidentalTripleSharp','SHARP3'],
    ['accidentalDoubleSharp','accidentalSharpSharp','accidentalDoubleSharpArabic','SHARP2','SHARP_SHARP'],
    ['accidentalSharp','accidentalBakiyeSharp','accidentalWyschnegradsky6TwelfthsSharp','accidentalSharpArabic','accidentalNaturalSharp','SHARP','NATURAL_SHARP'],
    ['accidentalFlat','accidentalKucukMucennebFlat','accidentalWyschnegradsky6TwelfthsFlat','accidentalFlatArabic','accidentalNaturalFlat','FLAT','NATURAL_FLAT'],
    ['accidentalDoubleFlat','accidentalDoubleFlatArabic','FLAT2'],
    ['accidentalTripleFlat','FLAT3'],
    ['accidentalThreeQuarterTonesSharpStein','accidentalWyschnegradsky9TwelfthsSharp','accidentalThreeQuarterTonesSharpArabic','SHARP_SLASH4','NINE_TWELFTH_SHARP'],
    ['accidentalQuarterToneSharpStein','accidentalWyschnegradsky3TwelfthsSharp','accidentalKomaSharp','accidentalQuarterToneSharpArabic','SHARP_SLASH','THREE_TWELFTH_SHARP'],
    ['accidentalQuarterToneFlatFilledReversed'],
    ['accidentalQuarterToneFlatStein','accidentalNarrowReversedFlat','accidentalKomaFlat','accidentalLowerOneUndecimalQuartertone','MIRRORED_FLAT'],
    ['accidentalQuarterToneFlatPenderecki'],
    ['accidentalThreeQuarterTonesFlatZimmermann','accidentalNarrowReversedFlatAndFlat','accidentalThreeQuarterTonesFlatCouper','MIRRORED_FLAT2'],
    ['accidentalFilledReversedFlatAndFlat'],
    ['accidentalBuyukMucennebFlat','FLAT_SLASH2'],
    ['accidentalBakiyeFlat','accidentalQuarterToneFlatArabic','accidentalOneQuarterToneFlatStockhausen','FLAT_SLASH'],
    ['accidentalKucukMucennebSharp','SHARP_SLASH3'],
    ['accidentalBuyukMucennebSharp','SHARP_SLASH2'],
    ['accidentalThreeQuarterTonesFlatArabic','accidentalThreeQuarterTonesFlatGrisey'],
    ['accidentalThreeQuarterTonesSharpStockhausen'],
    ['accidentalDoubleSharpThreeArrowsUp','DOUBLE_SHARP_THREE_ARROWS_UP'],
    ['accidentalDoubleSharpTwoArrowsUp','DOUBLE_SHARP_TWO_ARROWS_UP'],
    ['accidentalDoubleSharpOneArrowUp','accidentalFiveQuarterTonesSharpArrowUp','SHARP2_ARROW_UP','DOUBLE_SHARP_ONE_ARROW_UP'],
    ['accidentalDoubleSharpOneArrowDown','accidentalThreeQuarterTonesSharpArrowDown','SHARP2_ARROW_DOWN','DOUBLE_SHARP_ONE_ARROW_DOWN'],
    ['accidentalDoubleSharpTwoArrowsDown','DOUBLE_SHARP_TWO_ARROWS_DOWN'],
    ['accidentalDoubleSharpThreeArrowsDown','DOUBLE_SHARP_THREE_ARROWS_DOWN'],
    ['accidentalOneAndAHalfSharpsArrowUp'],
    ['accidentalOneAndAHalfSharpsArrowDown'],
    ['accidentalSharpThreeArrowsUp','SHARP_THREE_ARROWS_UP'],
    ['accidentalSharpTwoArrowsUp','SHARP_TWO_ARROWS_UP'],
    ['accidentalSharpOneArrowUp','accidentalThreeQuarterTonesSharpArrowUp','accidentalSharpRaisedStockhausen','SHARP_ARROW_UP','SHARP_ONE_ARROW_UP'],
    ['accidentalSharpOneArrowDown','accidentalQuarterToneSharpArrowDown','accidentalSharpLoweredStockhausen','SHARP_ARROW_DOWN','SHARP_ONE_ARROW_DOWN'],
    ['accidentalSharpTwoArrowsDown','SHARP_TWO_ARROWS_DOWN'],
    ['accidentalSharpThreeArrowsDown','SHARP_THREE_ARROWS_DOWN'],
    ['accidentalHalfSharpArrowUp'],
    ['accidentalHalfSharpArrowDown'],
    ['accidentalNaturalThreeArrowsUp','NATURAL_THREE_ARROWS_UP'],
    ['accidentalNaturalTwoArrowsUp','NATURAL_TWO_ARROWS_UP'],
    ['accidentalNaturalOneArrowUp','accidentalQuarterToneSharpNaturalArrowUp','accidentalNaturalRaisedStockhausen','NATURAL_ARROW_UP','NATURAL_ONE_ARROW_UP'],
    ['accidentalArrowUp','accidentalCombiningLower23Limit29LimitComma','accidentalRaisedStockhausen','ARROW_UP'],
    ['accidentalNaturalOneArrowDown','accidentalQuarterToneFlatNaturalArrowDown','accidentalNaturalLoweredStockhausen','NATURAL_ARROW_DOWN','NATURAL_ONE_ARROW_DOWN'],
    ['accidentalArrowDown','accidentalCombiningRaise23Limit29LimitComma','accidentalLoweredStockhausen','ARROW_DOWN'],
    ['accidentalNaturalTwoArrowsDown','NATURAL_TWO_ARROWS_DOWN'],
    ['accidentalNaturalThreeArrowsDown','NATURAL_THREE_ARROWS_DOWN'],
    ['accidentalReversedFlatArrowUp'],
    ['accidentalFilledReversedFlatArrowUp'],
    ['accidentalReversedFlatArrowDown'],
    ['accidentalFilledReversedFlatArrowDown'],
    ['accidentalFlatThreeArrowsUp','FLAT_THREE_ARROWS_UP'],
    ['accidentalFlatTwoArrowsUp','FLAT_TWO_ARROWS_UP'],
    ['accidentalFlatOneArrowUp','accidentalQuarterToneFlatArrowUp','accidentalFlatRaisedStockhausen','FLAT_ARROW_UP','FLAT_ONE_ARROW_UP'],
    ['accidentalFlatOneArrowDown','accidentalThreeQuarterTonesFlatArrowDown','accidentalFlatLoweredStockhausen','FLAT_ARROW_DOWN','FLAT_ONE_ARROW_DOWN'],
    ['accidentalFlatTwoArrowsDown','FLAT_TWO_ARROWS_DOWN'],
    ['accidentalFlatThreeArrowsDown','FLAT_THREE_ARROWS_DOWN'],
    ['accidentalReversedFlatAndFlatArrowUp'],
    ['accidentalFilledReversedFlatAndFlatArrowUp'],
    ['accidentalReversedFlatAndFlatArrowDown'],
    ['accidentalFilledReversedFlatAndFlatArrowDown'],
    ['accidentalDoubleFlatThreeArrowsUp','DOUBLE_FLAT_THREE_ARROWS_UP'],
    ['accidentalDoubleFlatTwoArrowsUp','DOUBLE_FLAT_TWO_ARROWS_UP'],
    ['accidentalDoubleFlatOneArrowUp','accidentalThreeQuarterTonesFlatArrowUp','FLAT2_ARROW_UP','DOUBLE_FLAT_ONE_ARROW_UP'],
    ['accidentalDoubleFlatOneArrowDown','accidentalFiveQuarterTonesFlatArrowDown','FLAT2_ARROW_DOWN','DOUBLE_FLAT_ONE_ARROW_DOWN'],
    ['accidentalDoubleFlatTwoArrowsDown','DOUBLE_FLAT_TWO_ARROWS_DOWN'],
    ['accidentalDoubleFlatThreeArrowsDown','DOUBLE_FLAT_THREE_ARROWS_DOWN'],
    ['accidentalSharpRepeatedLineStockhausen'],
    ['accidentalSharpRepeatedSpaceStockhausen'],
    ['accidentalFlatRepeatedLineStockhausen'],
    ['accidentalFlatRepeatedSpaceStockhausen'],
    ['accidentalRaiseTwoSeptimalCommas'],
    ['accidentalRaiseOneSeptimalComma'],
    ['accidentalLowerOneSeptimalComma'],
    ['accidentalLowerTwoSeptimalCommas'],
    ['accidentalRaiseOneUndecimalQuartertone','accidentalOneQuarterToneSharpStockhausen'],
    ['accidentalRaiseOneTridecimalQuartertone'],
    ['accidentalLowerOneTridecimalQuartertone'],
    ['accidentalCombiningRaise53LimitComma'],
    ['accidentalCombiningRaise17Schisma'],
    ['accidentalCombiningRaise19Schisma'],
    ['accidentalCombiningLower19Schisma'],
    ['accidentalCombiningLower17Schisma'],
    ['accidentalCombiningLower53LimitComma'],
    ['accidentalSori'],
    ['accidentalCombiningRaise31Schisma'],
    ['accidentalCombiningLower31Schisma'],
    ['accidentalKoron'],
    ['accidentalCombiningOpenCurlyBrace'],
    ['accidentalCombiningCloseCurlyBrace'],
    ['accidentalDoubleFlatEqualTempered'],
    ['accidentalFlatEqualTempered'],
    ['accidentalQuarterFlatEqualTempered'],
    ['accidentalNaturalEqualTempered'],
    ['accidentalQuarterSharpEqualTempered'],
    ['accidentalSharpEqualTempered'],
    ['accidentalDoubleSharpEqualTempered'],
    ['accidentalEnharmonicAlmostEqualTo'],
    ['accidentalEnharmonicEquals'],
    ['accidentalEnharmonicTilde'],
    ['medRenSharpCroix'],
    ['medRenNaturalWithCross'],
    ['medRenFlatSoftB'],
    ['medRenFlatHardB'],
    ['medRenFlatWithDot'],
    ['accidentalJohnstonPlus'],
    ['accidentalJohnstonMinus'],
    ['accidentalJohnstonEl'],
    ['accidentalJohnstonSeven'],
    ['accidentalJohnstonUp'],
    ['accidentalJohnstonDown'],
    ['accidentalJohnston13'],
    ['accidentalJohnston31'],
    ['accidentalSims4Up'],
    ['accidentalSims6Up'],
    ['accidentalSims12Up'],
    ['accidentalSims12Down'],
    ['accidentalSims6Down'],
    ['accidentalSims4Down'],
    ['accidentalWyschnegradsky11TwelfthsSharp'],
    ['accidentalWyschnegradsky10TwelfthsSharp'],
    ['accidentalWyschnegradsky8TwelfthsSharp'],
    ['accidentalWyschnegradsky7TwelfthsSharp'],
    ['accidentalWyschnegradsky5TwelfthsSharp'],
    ['accidentalWyschnegradsky4TwelfthsSharp'],
    ['accidentalWyschnegradsky2TwelfthsSharp'],
    ['accidentalWyschnegradsky1TwelfthsSharp'],
    ['accidentalWyschnegradsky1TwelfthsFlat'],
    ['accidentalWyschnegradsky2TwelfthsFlat'],
    ['accidentalWyschnegradsky3TwelfthsFlat'],
    ['accidentalWyschnegradsky4TwelfthsFlat'],
    ['accidentalWyschnegradsky5TwelfthsFlat'],
    ['accidentalWyschnegradsky7TwelfthsFlat'],
    ['accidentalWyschnegradsky8TwelfthsFlat'],
    ['accidentalWyschnegradsky9TwelfthsFlat'],
    ['accidentalWyschnegradsky10TwelfthsFlat'],
    ['accidentalWyschnegradsky11TwelfthsFlat'],
    ['accidentalXenakisOneThirdToneSharp'],
    ['accidentalXenakisTwoThirdTonesSharp'],
    ['accidentalQuarterToneSharpBusotti'],
    ['accidentalSharpOneHorizontalStroke'],
    ['accidentalThreeQuarterTonesSharpBusotti'],
    ['accidentalQuarterToneSharpWiggle'],
    ['accidentalTavenerSharp'],
    ['accidentalTavenerFlat'],
    ['accidentalCommaSlashUp'],
    ['accidentalCommaSlashDown'],
    ['accidentalWilsonPlus'],
    ['accidentalWilsonMinus'],
    ['accidentalLargeDoubleSharp'],
    ['accidentalQuarterToneSharp4'],
    ['accidentalQuarterToneFlat4'],
    ['accidentalSharpReversed'],
    ['accidentalNaturalReversed'],
    ['accidentalFlatTurned'],
    ['accidentalDoubleFlatReversed'],
    ['accidentalDoubleFlatTurned'],
    ['accidentalThreeQuarterTonesFlatTartini'],
    ['accidentalQuarterToneFlatVanBlankenburg'],
    ['accidentalTwoThirdTonesSharpFerneyhough'],
    ['accidentalOneThirdToneSharpFerneyhough'],
    ['accidentalOneQuarterToneSharpFerneyhough'],
    ['accidentalOneQuarterToneFlatFerneyhough'],
    ['accidentalOneThirdToneFlatFerneyhough'],
    ['accidentalTwoThirdTonesFlatFerneyhough'],
];


var TEXT_TO_CODE = {
    '#x': 3,
    'x': 4,
    '#': 5,
    'b': 6,
    'bb': 7,
    'bbb': 8,
    '#+': 9,
    '+': 10,
    'd': 12,
    'db': 14,
    'b//': 16,
    'b/': 17,
    'E': 18,
    '|b': 20,
    'x^3': 22,
    'x^2': 23,
    'x^': 24,
    'xv': 25,
    'xv2': 26,
    'xv3': 27,
    '#+^': 28,
    '#+v': 29,
    '#^3': 30,
    '#^2': 31,
    '#^': 32,
    '#v': 33,
    '#v2': 34,
    '#v3': 35,
    '+^': 36,
    '+v': 37,
    '^3': 38,
    '^2': 39,
    '^': 40,
    '/': 41,
    'v': 42,
    '\\': 43,
    'v2': 44,
    'v3': 45,
    'd^': 46,
    'dv': 48,
    'b^3': 50,
    'b^2': 51,
    'b^': 52,
    'bv': 53,
    'bv2': 54,
    'bv3': 55,
    'db^': 56,
    'dbv': 58,
    'bb^3': 60,
    'bb^2': 61,
    'bb^': 62,
    'bbv': 63,
    'bbv2': 64,
    'bbv3': 65,
    'u77': 70,
    'u7': 71,
    'd7': 72,
    'd77': 73,
    't': 74,
    'tt': 75,
    'd|': 76,
    "'''": 77,
    "''": 78,
    "'": 79,
    '`': 80,
    '``': 81,
    '```': 82,
    '{': 87,
    '}': 88,
    '_bb': 89,
    '_b': 90,
    '_d': 91,
    '_2': 92,
    '_t': 93,
    '_#': 94,
    '_x': 95,
    'aprx': 96,
    '=': 97,
    'j+': 104,
    'j-': 105,
    'ju7': 106,
    'jd7': 107,
    'j/': 108,
    'j\\': 109,
    'ju13': 110,
    'jd13': 111,
};


var SYMBOL_LAYOUT = {
    'accidentalJohnstonPlus': [0.0,0.25,0.3,0.0],
    'accidentalJohnstonMinus': [0.0,0.25,0.3,0.0],
};

function ImportGenerated() {
    return {
        CODE_TO_LABELS: CODE_TO_LABELS,
        TEXT_TO_CODE: TEXT_TO_CODE,
        SYMBOL_LAYOUT: SYMBOL_LAYOUT
    };
}
