var CODE_TO_LABELS = [
    null,
    ['noSym','NONE'],
    ['accidentalNatural','medRenNatural','NATURAL'],
    ['accidentalTripleSharp','SHARP3'],
    ['accidentalDoubleSharp','accidentalSharpSharp','SHARP2','SHARP_SHARP'],
    ['accidentalSharp','accidentalBakiyeSharp','SHARP','NATURAL_SHARP'],
    ['accidentalFlat','accidentalKucukMucennebFlat','FLAT','NATURAL_FLAT'],
    ['accidentalDoubleFlat','FLAT2'],
    ['accidentalTripleFlat','FLAT3'],
    ['accidentalThreeQuarterTonesSharpStein','accidentalWyschnegradsky9TwelfthsSharp','accidentalNaturalSharp','SHARP_SLASH4','NINE_TWELFTH_SHARP'],
    ['accidentalQuarterToneSharpStein','accidentalWyschnegradsky3TwelfthsSharp','accidentalKomaSharp','SHARP_SLASH','THREE_TWELFTH_SHARP'],
    ['accidentalQuarterToneFlatStein','accidentalNarrowReversedFlat','accidentalKomaFlat','MIRRORED_FLAT'],
    ['accidentalThreeQuarterTonesFlatZimmermann','accidentalNarrowReversedFlatAndFlat','MIRRORED_FLAT2'],
    ['accidentalBuyukMucennebFlat','FLAT_SLASH2'],
    ['accidentalBakiyeFlat','accidentalQuarterToneFlatArabic','FLAT_SLASH'],
    ['accidentalKucukMucennebSharp','SHARP_SLASH3'],
    ['accidentalBuyukMucennebSharp','SHARP_SLASH2'],
    ['accidentalThreeQuarterTonesFlatArabic'],
    ['accidentalDoubleSharpThreeArrowsUp','DOUBLE_SHARP_THREE_ARROWS_UP'],
    ['accidentalDoubleSharpTwoArrowsUp','DOUBLE_SHARP_TWO_ARROWS_UP'],
    ['accidentalDoubleSharpOneArrowUp','accidentalFiveQuarterTonesSharpArrowUp','SHARP2_ARROW_UP','DOUBLE_SHARP_ONE_ARROW_UP'],
    ['accidentalDoubleSharpOneArrowDown','accidentalThreeQuarterTonesSharpArrowDown','SHARP2_ARROW_DOWN','DOUBLE_SHARP_ONE_ARROW_DOWN'],
    ['accidentalDoubleSharpTwoArrowsDown','DOUBLE_SHARP_TWO_ARROWS_DOWN'],
    ['accidentalDoubleSharpThreeArrowsDown','DOUBLE_SHARP_THREE_ARROWS_DOWN'],
    ['accidentalSharpThreeArrowsUp','SHARP_THREE_ARROWS_UP'],
    ['accidentalSharpTwoArrowsUp','SHARP_TWO_ARROWS_UP'],
    ['accidentalSharpOneArrowUp','accidentalThreeQuarterTonesSharpArrowUp','SHARP_ARROW_UP','SHARP_ONE_ARROW_UP'],
    ['accidentalSharpOneArrowDown','accidentalQuarterToneSharpArrowDown','SHARP_ARROW_DOWN','SHARP_ONE_ARROW_DOWN'],
    ['accidentalSharpTwoArrowsDown','SHARP_TWO_ARROWS_DOWN'],
    ['accidentalSharpThreeArrowsDown','SHARP_THREE_ARROWS_DOWN'],
    ['accidentalNaturalThreeArrowsUp','NATURAL_THREE_ARROWS_UP'],
    ['accidentalNaturalTwoArrowsUp','NATURAL_TWO_ARROWS_UP'],
    ['accidentalNaturalOneArrowUp','accidentalQuarterToneSharpNaturalArrowUp','NATURAL_ARROW_UP','NATURAL_ONE_ARROW_UP'],
    ['accidentalArrowUp','accidentalCombiningLower23Limit29LimitComma','ARROW_UP'],
    ['accidentalNaturalOneArrowDown','accidentalQuarterToneFlatNaturalArrowDown','NATURAL_ARROW_DOWN','NATURAL_ONE_ARROW_DOWN'],
    ['accidentalArrowDown','accidentalCombiningRaise23Limit29LimitComma','ARROW_DOWN'],
    ['accidentalNaturalTwoArrowsDown','NATURAL_TWO_ARROWS_DOWN'],
    ['accidentalNaturalThreeArrowsDown','NATURAL_THREE_ARROWS_DOWN'],
    ['accidentalFlatThreeArrowsUp','FLAT_THREE_ARROWS_UP'],
    ['accidentalFlatTwoArrowsUp','FLAT_TWO_ARROWS_UP'],
    ['accidentalFlatOneArrowUp','accidentalQuarterToneFlatArrowUp','FLAT_ARROW_UP','FLAT_ONE_ARROW_UP'],
    ['accidentalFlatOneArrowDown','accidentalThreeQuarterTonesFlatArrowDown','FLAT_ARROW_DOWN','FLAT_ONE_ARROW_DOWN'],
    ['accidentalFlatTwoArrowsDown','FLAT_TWO_ARROWS_DOWN'],
    ['accidentalFlatThreeArrowsDown','FLAT_THREE_ARROWS_DOWN'],
    ['accidentalDoubleFlatThreeArrowsUp','DOUBLE_FLAT_THREE_ARROWS_UP'],
    ['accidentalDoubleFlatTwoArrowsUp','DOUBLE_FLAT_TWO_ARROWS_UP'],
    ['accidentalDoubleFlatOneArrowUp','accidentalThreeQuarterTonesFlatArrowUp','FLAT2_ARROW_UP','DOUBLE_FLAT_ONE_ARROW_UP'],
    ['accidentalDoubleFlatOneArrowDown','accidentalFiveQuarterTonesFlatArrowDown','FLAT2_ARROW_DOWN','DOUBLE_FLAT_ONE_ARROW_DOWN'],
    ['accidentalDoubleFlatTwoArrowsDown','DOUBLE_FLAT_TWO_ARROWS_DOWN'],
    ['accidentalDoubleFlatThreeArrowsDown','DOUBLE_FLAT_THREE_ARROWS_DOWN'],
];


var TEXT_TO_CODE = {
    '#x': 3,
    'x': 4,
    '#': 5,
    'b': 6,
    'bb': 7,
    'bbb': 8,
    '#+': 9,
    '+': 10,
    'd': 11,
    'db': 12,
    'x^3': 18,
    'x^2': 19,
    'x^': 20,
    'xv': 21,
    'xv2': 22,
    'xv3': 23,
    '#^3': 24,
    '#^2': 25,
    '#^': 26,
    '#v': 27,
    '#v2': 28,
    '#v3': 29,
    '^3': 30,
    '^2': 31,
    '^': 32,
    '/': 33,
    'v': 34,
    '\\': 35,
    'v2': 36,
    'v3': 37,
    'b^3': 38,
    'b^2': 39,
    'b^': 40,
    'bv': 41,
    'bv2': 42,
    'bv3': 43,
    'bb^3': 44,
    'bb^2': 45,
    'bb^': 46,
    'bbv': 47,
    'bbv2': 48,
    'bbv3': 49,
};


var SYMBOL_LAYOUT = {
    'accidentalNatural': [1.0,0.0,0.0,2.2],
    'medRenNatural': [1.0,0.0,0.0,2.2],
    'NATURAL': [1.0,0.0,0.0,2.2],
};

function ImportGenerated() {
    return {
        CODE_TO_LABELS: CODE_TO_LABELS,
        TEXT_TO_CODE: TEXT_TO_CODE,
        SYMBOL_LAYOUT: SYMBOL_LAYOUT
    };
}
