var CODE_TO_LABELS = [
    null,
    ['noSym','NONE'],
    ['accidentalNatural','medRenNatural','accidentalNaturalArabic','NATURAL'],
    ['accidentalTripleSharp','SHARP3'],
    ['accidentalDoubleSharp','accidentalSharpSharp','accidentalDoubleSharpArabic','SHARP2','SHARP_SHARP'],
    ['accidentalSharp','accidentalBakiyeSharp','accidentalWyschnegradsky6TwelfthsSharp','accidentalSharpArabic','accidentalNaturalSharp','SHARP','NATURAL_SHARP'],
    ['accidentalFlat','accidentalKucukMucennebFlat','accidentalWyschnegradsky6TwelfthsFlat','accidentalFlatArabic','accidentalNaturalFlat','FLAT','NATURAL_FLAT'],
    ['accidentalDoubleFlat','accidentalDoubleFlatArabic','FLAT2'],
    ['accidentalTripleFlat','FLAT3'],
    ['accidentalThreeQuarterTonesSharpStein','accidentalWyschnegradsky9TwelfthsSharp','accidentalThreeQuarterTonesSharpArabic','SHARP_SLASH4','NINE_TWELFTH_SHARP'],
    ['accidentalQuarterToneSharpStein','accidentalWyschnegradsky3TwelfthsSharp','accidentalKomaSharp','accidentalQuarterToneSharpArabic','SHARP_SLASH','THREE_TWELFTH_SHARP'],
    ['accidentalQuarterToneFlatFilledReversed'],
    ['accidentalQuarterToneFlatStein','accidentalNarrowReversedFlat','accidentalKomaFlat','accidentalLowerOneUndecimalQuartertone','MIRRORED_FLAT'],
    ['accidentalQuarterToneFlatPenderecki'],
    ['accidentalThreeQuarterTonesFlatZimmermann','accidentalNarrowReversedFlatAndFlat','accidentalThreeQuarterTonesFlatCouper','MIRRORED_FLAT2'],
    ['accidentalFilledReversedFlatAndFlat'],
    ['accidentalBuyukMucennebFlat','FLAT_SLASH2'],
    ['accidentalBakiyeFlat','accidentalQuarterToneFlatArabic','accidentalOneQuarterToneFlatStockhausen','FLAT_SLASH'],
    ['accidentalKucukMucennebSharp','SHARP_SLASH3'],
    ['accidentalBuyukMucennebSharp','SHARP_SLASH2'],
    ['accidentalThreeQuarterTonesFlatArabic','accidentalThreeQuarterTonesFlatGrisey'],
    ['accidentalThreeQuarterTonesSharpStockhausen'],
    ['accidentalDoubleSharpThreeArrowsUp','DOUBLE_SHARP_THREE_ARROWS_UP'],
    ['accidentalDoubleSharpTwoArrowsUp','DOUBLE_SHARP_TWO_ARROWS_UP'],
    ['accidentalDoubleSharpOneArrowUp','accidentalFiveQuarterTonesSharpArrowUp','SHARP2_ARROW_UP','DOUBLE_SHARP_ONE_ARROW_UP'],
    ['accidentalDoubleSharpOneArrowDown','accidentalThreeQuarterTonesSharpArrowDown','SHARP2_ARROW_DOWN','DOUBLE_SHARP_ONE_ARROW_DOWN'],
    ['accidentalDoubleSharpTwoArrowsDown','DOUBLE_SHARP_TWO_ARROWS_DOWN'],
    ['accidentalDoubleSharpThreeArrowsDown','DOUBLE_SHARP_THREE_ARROWS_DOWN'],
    ['accidentalOneAndAHalfSharpsArrowUp'],
    ['accidentalOneAndAHalfSharpsArrowDown'],
    ['accidentalSharpThreeArrowsUp','SHARP_THREE_ARROWS_UP'],
    ['accidentalSharpTwoArrowsUp','SHARP_TWO_ARROWS_UP'],
    ['accidentalSharpOneArrowUp','accidentalThreeQuarterTonesSharpArrowUp','accidentalSharpRaisedStockhausen','SHARP_ARROW_UP','SHARP_ONE_ARROW_UP'],
    ['accidentalSharpOneArrowDown','accidentalQuarterToneSharpArrowDown','accidentalSharpLoweredStockhausen','SHARP_ARROW_DOWN','SHARP_ONE_ARROW_DOWN'],
    ['accidentalSharpTwoArrowsDown','SHARP_TWO_ARROWS_DOWN'],
    ['accidentalSharpThreeArrowsDown','SHARP_THREE_ARROWS_DOWN'],
    ['accidentalHalfSharpArrowUp'],
    ['accidentalHalfSharpArrowDown'],
    ['accidentalNaturalThreeArrowsUp','NATURAL_THREE_ARROWS_UP'],
    ['accidentalNaturalTwoArrowsUp','NATURAL_TWO_ARROWS_UP'],
    ['accidentalNaturalOneArrowUp','accidentalQuarterToneSharpNaturalArrowUp','accidentalNaturalRaisedStockhausen','NATURAL_ARROW_UP','NATURAL_ONE_ARROW_UP'],
    ['accidentalArrowUp','accidentalCombiningLower23Limit29LimitComma','accidentalRaisedStockhausen','ARROW_UP'],
    ['accidentalNaturalOneArrowDown','accidentalQuarterToneFlatNaturalArrowDown','accidentalNaturalLoweredStockhausen','NATURAL_ARROW_DOWN','NATURAL_ONE_ARROW_DOWN'],
    ['accidentalArrowDown','accidentalCombiningRaise23Limit29LimitComma','accidentalLoweredStockhausen','ARROW_DOWN'],
    ['accidentalNaturalTwoArrowsDown','NATURAL_TWO_ARROWS_DOWN'],
    ['accidentalNaturalThreeArrowsDown','NATURAL_THREE_ARROWS_DOWN'],
    ['accidentalReversedFlatArrowUp'],
    ['accidentalFilledReversedFlatArrowUp'],
    ['accidentalReversedFlatArrowDown'],
    ['accidentalFilledReversedFlatArrowDown'],
    ['accidentalFlatThreeArrowsUp','FLAT_THREE_ARROWS_UP'],
    ['accidentalFlatTwoArrowsUp','FLAT_TWO_ARROWS_UP'],
    ['accidentalFlatOneArrowUp','accidentalQuarterToneFlatArrowUp','accidentalFlatRaisedStockhausen','FLAT_ARROW_UP','FLAT_ONE_ARROW_UP'],
    ['accidentalFlatOneArrowDown','accidentalThreeQuarterTonesFlatArrowDown','accidentalFlatLoweredStockhausen','FLAT_ARROW_DOWN','FLAT_ONE_ARROW_DOWN'],
    ['accidentalFlatTwoArrowsDown','FLAT_TWO_ARROWS_DOWN'],
    ['accidentalFlatThreeArrowsDown','FLAT_THREE_ARROWS_DOWN'],
    ['accidentalReversedFlatAndFlatArrowUp'],
    ['accidentalFilledReversedFlatAndFlatArrowUp'],
    ['accidentalReversedFlatAndFlatArrowDown'],
    ['accidentalFilledReversedFlatAndFlatArrowDown'],
    ['accidentalDoubleFlatThreeArrowsUp','DOUBLE_FLAT_THREE_ARROWS_UP'],
    ['accidentalDoubleFlatTwoArrowsUp','DOUBLE_FLAT_TWO_ARROWS_UP'],
    ['accidentalDoubleFlatOneArrowUp','accidentalThreeQuarterTonesFlatArrowUp','FLAT2_ARROW_UP','DOUBLE_FLAT_ONE_ARROW_UP'],
    ['accidentalDoubleFlatOneArrowDown','accidentalFiveQuarterTonesFlatArrowDown','FLAT2_ARROW_DOWN','DOUBLE_FLAT_ONE_ARROW_DOWN'],
    ['accidentalDoubleFlatTwoArrowsDown','DOUBLE_FLAT_TWO_ARROWS_DOWN'],
    ['accidentalDoubleFlatThreeArrowsDown','DOUBLE_FLAT_THREE_ARROWS_DOWN'],
    ['accidentalSharpRepeatedLineStockhausen'],
    ['accidentalSharpRepeatedSpaceStockhausen'],
    ['accidentalFlatRepeatedLineStockhausen'],
    ['accidentalFlatRepeatedSpaceStockhausen'],
    ['accidentalRaiseTwoSeptimalCommas'],
    ['accidentalRaiseOneSeptimalComma'],
    ['accidentalLowerOneSeptimalComma'],
    ['accidentalLowerTwoSeptimalCommas'],
    ['accidentalRaiseOneUndecimalQuartertone','accidentalOneQuarterToneSharpStockhausen'],
    ['accidentalRaiseOneTridecimalQuartertone'],
    ['accidentalLowerOneTridecimalQuartertone'],
    ['accidentalCombiningRaise53LimitComma'],
    ['accidentalCombiningRaise17Schisma'],
    ['accidentalCombiningRaise19Schisma','accSagittalAcute'],
    ['accidentalCombiningLower19Schisma','accSagittalGrave'],
    ['accidentalCombiningLower17Schisma'],
    ['accidentalCombiningLower53LimitComma'],
    ['accidentalSori'],
    ['accidentalCombiningRaise31Schisma'],
    ['accidentalCombiningLower31Schisma'],
    ['accidentalKoron'],
    ['accidentalCombiningOpenCurlyBrace'],
    ['accidentalCombiningCloseCurlyBrace'],
    ['accidentalDoubleFlatEqualTempered'],
    ['accidentalFlatEqualTempered'],
    ['accidentalQuarterFlatEqualTempered'],
    ['accidentalNaturalEqualTempered'],
    ['accidentalQuarterSharpEqualTempered'],
    ['accidentalSharpEqualTempered'],
    ['accidentalDoubleSharpEqualTempered'],
    ['accidentalEnharmonicAlmostEqualTo'],
    ['accidentalEnharmonicEquals'],
    ['accidentalEnharmonicTilde'],
    ['medRenSharpCroix'],
    ['medRenNaturalWithCross'],
    ['medRenFlatSoftB'],
    ['medRenFlatHardB'],
    ['medRenFlatWithDot'],
    ['accidentalJohnstonPlus'],
    ['accidentalJohnstonMinus'],
    ['accidentalJohnstonEl'],
    ['accidentalJohnstonSeven'],
    ['accidentalJohnstonUp'],
    ['accidentalJohnstonDown'],
    ['accidentalJohnston13'],
    ['accidentalJohnston31'],
    ['accidentalSims4Up'],
    ['accidentalSims6Up'],
    ['accidentalSims12Up'],
    ['accidentalSims12Down'],
    ['accidentalSims6Down'],
    ['accidentalSims4Down'],
    ['accidentalWyschnegradsky11TwelfthsSharp'],
    ['accidentalWyschnegradsky10TwelfthsSharp'],
    ['accidentalWyschnegradsky8TwelfthsSharp'],
    ['accidentalWyschnegradsky7TwelfthsSharp'],
    ['accidentalWyschnegradsky5TwelfthsSharp'],
    ['accidentalWyschnegradsky4TwelfthsSharp'],
    ['accidentalWyschnegradsky2TwelfthsSharp'],
    ['accidentalWyschnegradsky1TwelfthsSharp'],
    ['accidentalWyschnegradsky1TwelfthsFlat'],
    ['accidentalWyschnegradsky2TwelfthsFlat'],
    ['accidentalWyschnegradsky3TwelfthsFlat'],
    ['accidentalWyschnegradsky4TwelfthsFlat'],
    ['accidentalWyschnegradsky5TwelfthsFlat'],
    ['accidentalWyschnegradsky7TwelfthsFlat'],
    ['accidentalWyschnegradsky8TwelfthsFlat'],
    ['accidentalWyschnegradsky9TwelfthsFlat'],
    ['accidentalWyschnegradsky10TwelfthsFlat'],
    ['accidentalWyschnegradsky11TwelfthsFlat'],
    ['accidentalXenakisOneThirdToneSharp'],
    ['accidentalXenakisTwoThirdTonesSharp'],
    ['accidentalQuarterToneSharpBusotti'],
    ['accidentalSharpOneHorizontalStroke'],
    ['accidentalThreeQuarterTonesSharpBusotti'],
    ['accidentalQuarterToneSharpWiggle'],
    ['accidentalTavenerSharp'],
    ['accidentalTavenerFlat'],
    ['accidentalCommaSlashUp'],
    ['accidentalCommaSlashDown'],
    ['accidentalWilsonPlus'],
    ['accidentalWilsonMinus'],
    ['accidentalLargeDoubleSharp'],
    ['accidentalQuarterToneSharp4'],
    ['accidentalQuarterToneFlat4'],
    ['accidentalSharpReversed'],
    ['accidentalNaturalReversed'],
    ['accidentalFlatTurned'],
    ['accidentalDoubleFlatReversed'],
    ['accidentalDoubleFlatTurned'],
    ['accidentalThreeQuarterTonesFlatTartini'],
    ['accidentalQuarterToneFlatVanBlankenburg'],
    ['accidentalTwoThirdTonesSharpFerneyhough'],
    ['accidentalOneThirdToneSharpFerneyhough'],
    ['accidentalOneQuarterToneSharpFerneyhough'],
    ['accidentalOneQuarterToneFlatFerneyhough'],
    ['accidentalOneThirdToneFlatFerneyhough'],
    ['accidentalTwoThirdTonesFlatFerneyhough'],
    ['accSagittalDoubleSharp'],
    ['accSagittalDoubleSharp5v7kDown'],
    ['accSagittalDoubleSharp5CDown'],
    ['accSagittalDoubleSharp7CDown'],
    ['accSagittalDoubleSharp25SDown'],
    ['accSagittalSharp35LUp'],
    ['accSagittalSharp11LUp'],
    ['accSagittalSharp11MUp'],
    ['accSagittalSharp35MUp'],
    ['accSagittalSharp25SUp'],
    ['accSagittalSharp7CUp'],
    ['accSagittalSharp5CUp'],
    ['accSagittalSharp5v7kUp'],
    ['accSagittalSharp','SAGITTAL_SHARP'],
    ['accSagittalSharp5v7kDown','SAGITTAL_SHARP5V7KD'],
    ['accSagittalSharp5CDown','SAGITTAL_SHARP5CD'],
    ['accSagittalSharp7CDown','SAGITTAL_SHARP7CD'],
    ['accSagittalSharp25SDown','SAGITTAL_SHARP25SD'],
    ['accSagittal35LargeDiesisUp','SAGITTAL_35LDU'],
    ['accSagittal11LargeDiesisUp','SAGITTAL_11LDU'],
    ['accSagittal11MediumDiesisUp','SAGITTAL_11MDU'],
    ['accSagittal35MediumDiesisUp','SAGITTAL_35MDU'],
    ['accSagittal25SmallDiesisUp','SAGITTAL_25SDU'],
    ['accSagittal7CommaUp','SAGITTAL_7CU'],
    ['accSagittal5CommaUp','SAGITTAL_5CU'],
    ['accSagittal5v7KleismaUp','SAGITTAL_5V7KU'],
    ['accSagittal5v7KleismaDown','SAGITTAL_5V7KD'],
    ['accSagittal5CommaDown','SAGITTAL_5CD'],
    ['accSagittal7CommaDown','SAGITTAL_7CD'],
    ['accSagittal25SmallDiesisDown','SAGITTAL_25SDD'],
    ['accSagittal35MediumDiesisDown','SAGITTAL_35MDD'],
    ['accSagittal11MediumDiesisDown','SAGITTAL_11MDD'],
    ['accSagittal11LargeDiesisDown','SAGITTAL_11LDD'],
    ['accSagittal35LargeDiesisDown','SAGITTAL_35LDD'],
    ['accSagittalFlat25SUp','SAGITTAL_FLAT25SU'],
    ['accSagittalFlat7CUp','SAGITTAL_FLAT7CU'],
    ['accSagittalFlat5CUp','SAGITTAL_FLAT5CU'],
    ['accSagittalFlat5v7kUp','SAGITTAL_FLAT5V7KU'],
    ['accSagittalFlat','SAGITTAL_FLAT'],
    ['accSagittalFlat5v7kDown'],
    ['accSagittalFlat5CDown'],
    ['accSagittalFlat7CDown'],
    ['accSagittalFlat25SDown'],
    ['accSagittalFlat35MDown'],
    ['accSagittalFlat11MDown'],
    ['accSagittalFlat11LDown'],
    ['accSagittalFlat35LDown'],
    ['accSagittalDoubleFlat25SUp'],
    ['accSagittalDoubleFlat7CUp'],
    ['accSagittalDoubleFlat5CUp'],
    ['accSagittalDoubleFlat5v7kUp'],
    ['accSagittalDoubleFlat'],
    ['accSagittalDoubleSharp7v11kDown'],
    ['accSagittalDoubleSharp17CDown'],
    ['accSagittalDoubleSharp55CDown'],
    ['accSagittalDoubleSharp7v11CDown'],
    ['accSagittalDoubleSharp5v11SDown'],
    ['accSagittalSharp5v11SUp'],
    ['accSagittalSharp7v11CUp'],
    ['accSagittalSharp55CUp'],
    ['accSagittalSharp17CUp'],
    ['accSagittalSharp7v11kUp'],
    ['accSagittalSharp7v11kDown'],
    ['accSagittalSharp17CDown'],
    ['accSagittalSharp55CDown'],
    ['accSagittalSharp7v11CDown'],
    ['accSagittalSharp5v11SDown'],
    ['accSagittal5v11SmallDiesisUp'],
    ['accSagittal7v11CommaUp'],
    ['accSagittal55CommaUp'],
    ['accSagittal17CommaUp'],
    ['accSagittal7v11KleismaUp'],
    ['accSagittal7v11KleismaDown'],
    ['accSagittal17CommaDown'],
    ['accSagittal55CommaDown'],
    ['accSagittal7v11CommaDown'],
    ['accSagittal5v11SmallDiesisDown'],
    ['accSagittalFlat5v11SUp'],
    ['accSagittalFlat7v11CUp'],
    ['accSagittalFlat55CUp'],
    ['accSagittalFlat17CUp'],
    ['accSagittalFlat7v11kUp'],
    ['accSagittalFlat7v11kDown'],
    ['accSagittalFlat17CDown'],
    ['accSagittalFlat55CDown'],
    ['accSagittalFlat7v11CDown'],
    ['accSagittalFlat5v11SDown'],
    ['accSagittalDoubleFlat5v11SUp'],
    ['accSagittalDoubleFlat7v11CUp'],
    ['accSagittalDoubleFlat55CUp'],
    ['accSagittalDoubleFlat17CUp'],
    ['accSagittalDoubleFlat7v11kUp'],
    ['accSagittalDoubleSharp23CDown'],
    ['accSagittalDoubleSharp5v19CDown'],
    ['accSagittalDoubleSharp5v23SDown'],
    ['accSagittalSharp5v23SUp'],
    ['accSagittalSharp5v19CUp'],
    ['accSagittalSharp23CUp'],
    ['accSagittalSharp23CDown'],
    ['accSagittalSharp5v19CDown'],
    ['accSagittalSharp5v23SDown'],
    ['accSagittal5v23SmallDiesisUp'],
    ['accSagittal5v19CommaUp'],
    ['accSagittal23CommaUp'],
    ['accSagittal23CommaDown'],
    ['accSagittal5v19CommaDown'],
    ['accSagittal5v23SmallDiesisDown'],
    ['accSagittalFlat5v23SUp'],
    ['accSagittalFlat5v19CUp'],
    ['accSagittalFlat23CUp'],
    ['accSagittalFlat23CDown'],
    ['accSagittalFlat5v19CDown'],
    ['accSagittalFlat5v23SDown'],
    ['accSagittalDoubleFlat5v23SUp'],
    ['accSagittalDoubleFlat5v19CUp'],
    ['accSagittalDoubleFlat23CUp'],
    ['accSagittalDoubleSharp19sDown'],
    ['accSagittalDoubleSharp17kDown'],
    ['accSagittalDoubleSharp143CDown'],
    ['accSagittalDoubleSharp11v49CDown'],
    ['accSagittalDoubleSharp19CDown'],
    ['accSagittalDoubleSharp7v19CDown'],
    ['accSagittalDoubleSharp49SDown'],
    ['accSagittalDoubleSharp23SDown'],
    ['accSagittalSharp5v13LUp'],
    ['accSagittalSharp11v19LUp'],
    ['accSagittalSharp49LUp'],
    ['accSagittalSharp5v49MUp'],
    ['accSagittalSharp49MUp'],
    ['accSagittalSharp11v19MUp'],
    ['accSagittalSharp5v13MUp'],
    ['accSagittalSharp23SUp'],
    ['accSagittalSharp49SUp'],
    ['accSagittalSharp7v19CUp'],
    ['accSagittalSharp19CUp'],
    ['accSagittalSharp11v49CUp'],
    ['accSagittalSharp143CUp'],
    ['accSagittalSharp17kUp'],
    ['accSagittalSharp19sUp'],
    ['accSagittalSharp19sDown'],
    ['accSagittalSharp17kDown'],
    ['accSagittalSharp143CDown'],
    ['accSagittalSharp11v49CDown'],
    ['accSagittalSharp19CDown'],
    ['accSagittalSharp7v19CDown'],
    ['accSagittalSharp49SDown'],
    ['accSagittalSharp23SDown'],
    ['accSagittal5v13LargeDiesisUp'],
    ['accSagittal11v19LargeDiesisUp'],
    ['accSagittal49LargeDiesisUp'],
    ['accSagittal5v49MediumDiesisUp'],
    ['accSagittal49MediumDiesisUp'],
    ['accSagittal11v19MediumDiesisUp'],
    ['accSagittal5v13MediumDiesisUp'],
    ['accSagittal23SmallDiesisUp'],
    ['accSagittal49SmallDiesisUp'],
    ['accSagittal7v19CommaUp'],
    ['accSagittal19CommaUp'],
    ['accSagittal11v49CommaUp'],
    ['accSagittal143CommaUp'],
    ['accSagittal17KleismaUp'],
    ['accSagittal19SchismaUp'],
    ['accSagittal19SchismaDown'],
    ['accSagittal17KleismaDown'],
    ['accSagittal143CommaDown'],
    ['accSagittal11v49CommaDown'],
    ['accSagittal19CommaDown'],
    ['accSagittal7v19CommaDown'],
    ['accSagittal49SmallDiesisDown'],
    ['accSagittal23SmallDiesisDown'],
    ['accSagittal5v13MediumDiesisDown'],
    ['accSagittal11v19MediumDiesisDown'],
    ['accSagittal49MediumDiesisDown'],
    ['accSagittal5v49MediumDiesisDown'],
    ['accSagittal49LargeDiesisDown'],
    ['accSagittal11v19LargeDiesisDown'],
    ['accSagittal5v13LargeDiesisDown'],
    ['accSagittalFlat23SUp'],
    ['accSagittalFlat49SUp'],
    ['accSagittalFlat7v19CUp'],
    ['accSagittalFlat19CUp'],
    ['accSagittalFlat11v49CUp'],
    ['accSagittalFlat143CUp'],
    ['accSagittalFlat17kUp'],
    ['accSagittalFlat19sUp'],
    ['accSagittalFlat19sDown'],
    ['accSagittalFlat17kDown'],
    ['accSagittalFlat143CDown'],
    ['accSagittalFlat11v49CDown'],
    ['accSagittalFlat19CDown'],
    ['accSagittalFlat7v19CDown'],
    ['accSagittalFlat49SDown'],
    ['accSagittalFlat23SDown'],
    ['accSagittalFlat5v13MDown'],
    ['accSagittalFlat11v19MDown'],
    ['accSagittalFlat49MDown'],
    ['accSagittalFlat5v49MDown'],
    ['accSagittalFlat49LDown'],
    ['accSagittalFlat11v19LDown'],
    ['accSagittalFlat5v13LDown'],
    ['accSagittalDoubleFlat23SUp'],
    ['accSagittalDoubleFlat49SUp'],
    ['accSagittalDoubleFlat7v19CUp'],
    ['accSagittalDoubleFlat19CUp'],
    ['accSagittalDoubleFlat11v49CUp'],
    ['accSagittalDoubleFlat143CUp'],
    ['accSagittalDoubleFlat17kUp'],
    ['accSagittalDoubleFlat19sUp'],
    ['accSagittalShaftUp'],
    ['accSagittalShaftDown'],
];


var TEXT_TO_CODE = {
    'n': 2,
    '#x': 3,
    'x': 4,
    '#': 5,
    'b': 6,
    'bb': 7,
    'bbb': 8,
    '#+': 9,
    '+': 10,
    'D': 11,
    'd': 12,
    'B': 13,
    'db': 14,
    'Db': 15,
    'b//': 16,
    'b/': 17,
    'E': 18,
    'E|': 19,
    '|b': 20,
    '|E': 21,
    'x^3': 22,
    'x^2': 23,
    'x^': 24,
    'xv': 25,
    'xv2': 26,
    'xv3': 27,
    '#+^': 28,
    '#+v': 29,
    '#^3': 30,
    '#^2': 31,
    '#^': 32,
    '#v': 33,
    '#v2': 34,
    '#v3': 35,
    '+^': 36,
    '+v': 37,
    '^3': 38,
    '^2': 39,
    '^': 40,
    '/': 41,
    'v': 42,
    '\\': 43,
    'v2': 44,
    'v3': 45,
    'd^': 46,
    'D^': 47,
    'dv': 48,
    'Dv': 49,
    'b^3': 50,
    'b^2': 51,
    'b^': 52,
    'bv': 53,
    'bv2': 54,
    'bv3': 55,
    'db^': 56,
    'Db^': 57,
    'dbv': 58,
    'Dbv': 59,
    'bb^3': 60,
    'bb^2': 61,
    'bb^': 62,
    'bbv': 63,
    'bbv2': 64,
    'bbv3': 65,
    '#>': 66,
    '#|>': 67,
    'b>': 68,
    'b|>': 69,
    'u77': 70,
    'u7': 71,
    'd7': 72,
    'd77': 73,
    't': 74,
    'tt': 75,
    'd|': 76,
    "'''": 77,
    "''": 78,
    "'": 79,
    '`': 80,
    '``': 81,
    '```': 82,
    '>||': 83,
    '>|': 84,
    '<|': 85,
    '|>': 86,
    '{': 87,
    '}': 88,
    '_bb': 89,
    '_b': 90,
    '_d': 91,
    '_2': 92,
    '_t': 93,
    '_#': 94,
    '_x': 95,
    'aprx': 96,
    '=': 97,
    '~': 98,
    'j+': 104,
    'j-': 105,
    'ju7': 106,
    'jd7': 107,
    'j/': 108,
    'j\\': 109,
    'ju13': 110,
    'jd13': 111,
    's^3': 112,
    's^2': 113,
    's^': 114,
    'sv': 115,
    'sv2': 116,
    'sv3': 117,
    '#+=': 118,
    '#+-': 119,
    '#=': 120,
    '#-': 121,
    '+=': 122,
    '+-': 123,
    '|=': 124,
    '|-': 125,
    'h=': 126,
    'h-': 127,
    'h': 128,
    'b=': 129,
    'b-': 130,
    'bh=': 131,
    'bh-': 132,
    'bh': 133,
    'bb=': 134,
    'bb-': 135,
    '/X\\': 164,
    '/X)': 165,
    'X\\': 166,
    'X)': 167,
    ')X(': 168,
    '(|||\\': 169,
    '(|||)': 170,
    '/|||\\': 171,
    '/|||)': 172,
    '=|||': 173,
    '|||)': 174,
    '/|||': 175,
    '|||(': 176,
    '/||\\': 177,
    '/||)': 178,
    '||\\': 179,
    '||)': 180,
    ')||(': 181,
    '(|\\': 182,
    '(|)': 183,
    '/|\\': 184,
    '/|)': 185,
    '=|': 186,
    '|)': 187,
    '/|': 188,
    '|(': 189,
    '!(': 190,
    '\\!': 191,
    '!)': 192,
    '=!': 193,
    '\\!)': 194,
    '\\!/': 195,
    '(!)': 196,
    '(!/': 197,
    ')!!(': 198,
    '!!)': 199,
    '!!/': 200,
    '\\!!)': 201,
    '\\!!/': 202,
    '!!!(': 203,
    '\\!!!': 204,
    '!!!)': 205,
    '=!!!': 206,
    '\\!!!)': 207,
    '\\!!!/': 208,
    '(!!!)': 209,
    '(!!!/': 210,
    ')Y(': 211,
    'Y)': 212,
    'Y/': 213,
    '\\Y)': 214,
    '\\Y/': 215,
    '=X': 216,
    '(X(': 217,
    '/X': 218,
    ')X~': 219,
    '~X(': 220,
    '(|||(': 221,
    '(|||': 222,
    '|||\\': 223,
    '~|||(': 224,
    ')|||(': 225,
    '=||': 226,
    '(||(': 227,
    '/||': 228,
    ')||~': 229,
    '~||(': 230,
    '(|(': 231,
    '(|': 232,
    '|\\': 233,
    '~|(': 234,
    ')|(': 235,
    ')!(': 236,
    '~!(': 237,
    '!/': 238,
    '(!': 239,
    '(!(': 240,
    '~!!(': 241,
    ')!!~': 242,
    '\\!!': 243,
    '(!!(': 244,
    '=!!': 245,
    ')!!!(': 246,
    '~!!!(': 247,
    '!!!/': 248,
    '(!!!': 249,
    '(!!!(': 250,
    '~Y(': 251,
    ')Y~': 252,
    '\\Y': 253,
    '(Y(': 254,
    '=Y': 255,
    '/X~': 256,
    ')X)': 257,
    'X~': 258,
    '/|||~': 259,
    ')/|||': 260,
    '|||~': 261,
    '/||~': 262,
    ')||)': 263,
    '||~': 264,
    '/|~': 265,
    ')/|': 266,
    '|~': 267,
    '!~': 268,
    ')\\!': 269,
    '\\!~': 270,
    '!!~': 271,
    ')!!)': 272,
    '\\!!~': 273,
    '!!!~': 274,
    ')\\!!!': 275,
    '\\!!!~': 276,
    'Y~': 277,
    ')Y)': 278,
    '\\Y~': 279,
    '(X~': 280,
    ')=X': 281,
    '~X\\': 282,
    '~X)': 283,
    '(X': 284,
    ')/X': 285,
    '~~X': 286,
    ')~X': 287,
    ')|||=': 288,
    '|||=': 289,
    '|||\\)': 290,
    ')/|||\\': 291,
    '(/|||': 292,
    '(|||~': 293,
    ')=|||': 294,
    '~|||\\': 295,
    '~|||)': 296,
    ')|||)': 297,
    ')|||~': 298,
    '~~|||': 299,
    ')~|||': 300,
    '~|||': 301,
    ')|||': 302,
    '(||~': 303,
    ')=||': 304,
    '~||\\': 305,
    '~||)': 306,
    '(||': 307,
    ')/||': 308,
    '~~||': 309,
    ')~||': 310,
    ')|=': 311,
    '|\\\\': 312,
    '|\\)': 313,
    ')/|\\': 314,
    '(/|': 315,
    '(|~': 316,
    ')=|': 317,
    '~|\\': 318,
    '~|)': 319,
    ')|)': 320,
    ')|~': 321,
    '~~|': 322,
    ')~|': 323,
    '~|': 324,
    ')|': 325,
    ')!': 326,
    '~!': 327,
    ')~!': 328,
    '~~!': 329,
    ')!~': 330,
    ')!)': 331,
    '~!)': 332,
    '~!/': 333,
    ')=!': 334,
    '(!~': 335,
    '(\\!': 336,
    ')\\!/': 337,
    '!/)': 338,
    '!=': 339,
    ')!=': 340,
    ')~!!': 341,
    '~~!!': 342,
    ')\\!!': 343,
    '(!!': 344,
    '~!!)': 345,
    '~!!/': 346,
    ')=!!': 347,
    '(!!~': 348,
    ')!!!': 349,
    '~!!!': 350,
    ')~!!!': 351,
    '~~!!!': 352,
    ')!!!~': 353,
    ')!!!)': 354,
    '~!!!)': 355,
    '~!!!/': 356,
    ')=!!!': 357,
    '(!!!~': 358,
    '(\\!!!': 359,
    ')\\!!!/': 360,
    '!!!/)': 361,
    '!!!=': 362,
    ')!!!=': 363,
    ')~Y': 364,
    '~~Y': 365,
    ')\\Y': 366,
    '(Y': 367,
    '~Y)': 368,
    '~Y/': 369,
    ')=Y': 370,
    '(Y~': 371,
    '|': 372,
    '!': 373,
};


var SYMBOL_LAYOUT = {
    'accidentalRaiseOneSeptimalComma': [[-0.2,0.0,0.0,0.0], [-0.2,0.0,0.0,0.0]],
    'accidentalLowerOneSeptimalComma': [[-0.2,0.0,0.0,0.0], [-0.2,0.0,0.0,0.0]],
    'accidentalLowerTwoSeptimalCommas': [[-0.2,0.0,0.0,0.0], [-0.2,0.0,0.0,0.0]],
    'accidentalJohnstonPlus': [[0.0,0.0,0.15,0.0], [0.0,0.3,0.15,0.0]],
    'accidentalJohnstonMinus': [[0.0,0.0,0.15,0.0], [0.0,0.3,0.15,0.0]],
    'accidentalJohnstonEl': [[-0.2,0.0,0.0,0.0], [-0.2,0.0,0.0,0.0]],
};

function ImportGenerated() {
    return {
        CODE_TO_LABELS: CODE_TO_LABELS,
        TEXT_TO_CODE: TEXT_TO_CODE,
        SYMBOL_LAYOUT: SYMBOL_LAYOUT
    };
}
